# Based on https://github.com/commercialhaskell/stack/wiki/Travis

sudo: false # Use new caching docker based infrastructure
cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
    - libgmp-dev

matrix:
  include:
  - env: GHCVER=7.10.2 STACK_YAML=stack-7.10.yaml
  # - env: GHCVER=head   STACK_YAML=stack-7.11.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-head
  # allow_failures:
  #   - env: GHCVER=head STACK_YAML=stack-7.11.yaml

before_install:
  # ghc
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar xz -C ~/.local/bin
  - chmod a+x ~/.local/bin/stack
  # versions
  - stack +RTS -N1 -RTS --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"

install:
  - ./travis_long stack --no-terminal --skip-ghc-check setup 7.10
  - ./travis_long stack --no-terminal --skip-ghc-check setup
  - ./travis_long stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test
  - stack --no-terminal --skip-ghc-check haddock

notifications:
  irc: "irc.freenode.org#haskell-refactorer"

# EOF
