flags: {}
packages:
- '.'
- location:
    git: git@github.com:mpickering/refact
    commit: 07fa5ff2ae554dcaf9ad93c04e195259be5dddd0
  extra-dep: true
extra-deps:
- cabal-helper-0.3.6.0
resolver: nightly-2015-06-25
